/* Automatically generated by create_config - do not modify */
#define TARGET_I386 1
#define TARGET_NAME "i386"
#define TARGET_I386 1
#define CONFIG_KVM 1
#define CONFIG_VHOST_NET 1
#define CONFIG_SOFTMMU 1
#define CONFIG_I386_DIS 1
#define CONFIG_I386_DIS 1
