# Automatically generated by configure - do not modify
TARGET_S390X=y
TARGET_NAME=s390x
TARGET_BASE_ARCH=s390x
TARGET_ABI_DIR=s390x
TARGET_WORDS_BIGENDIAN=y
CONFIG_USER_ONLY=y
CONFIG_QEMU_INTERP_PREFIX="/usr/gnemul/qemu-s390x"
CONFIG_LINUX_USER=y
TARGET_XML_FILES= /home/coldfunction/qCUDA/qcu-device/gdb-xml/s390x-core64.xml /home/coldfunction/qCUDA/qcu-device/gdb-xml/s390-acr.xml /home/coldfunction/qCUDA/qcu-device/gdb-xml/s390-fpr.xml /home/coldfunction/qCUDA/qcu-device/gdb-xml/s390-vx.xml
CONFIG_USE_GUEST_BASE=y
CONFIG_I386_DIS=y
CONFIG_S390_DIS=y
LDFLAGS+= 
QEMU_CFLAGS+=
