/* Automatically generated by create_config - do not modify */
#define TARGET_S390X 1
#define TARGET_NAME "s390x"
#define TARGET_S390X 1
#define TARGET_WORDS_BIGENDIAN 1
#define CONFIG_USER_ONLY 1
#define CONFIG_QEMU_INTERP_PREFIX "/usr/gnemul/qemu-s390x"
#define CONFIG_LINUX_USER 1
#define CONFIG_USE_GUEST_BASE 1
#define CONFIG_I386_DIS 1
#define CONFIG_S390_DIS 1
