/* Automatically generated by create_config - do not modify */
#define TARGET_ARM 1
#define TARGET_NAME "armeb"
#define TARGET_ARM 1
#define TARGET_WORDS_BIGENDIAN 1
#define CONFIG_USER_ONLY 1
#define CONFIG_QEMU_INTERP_PREFIX "/usr/gnemul/qemu-armeb"
#define CONFIG_LINUX_USER 1
#define TARGET_HAS_BFLT 1
#define CONFIG_USE_GUEST_BASE 1
#define CONFIG_I386_DIS 1
#define CONFIG_ARM_DIS 1
#define CONFIG_ARM_A64_DIS 1
