/* Automatically generated by create_config - do not modify */
#define TARGET_LM32 1
#define TARGET_NAME "lm32"
#define TARGET_LM32 1
#define TARGET_WORDS_BIGENDIAN 1
#define CONFIG_SOFTMMU 1
#define CONFIG_I386_DIS 1
#define CONFIG_LM32_DIS 1
