# Automatically generated by configure - do not modify
TARGET_M68K=y
TARGET_NAME=m68k
TARGET_BASE_ARCH=m68k
TARGET_ABI_DIR=m68k
TARGET_WORDS_BIGENDIAN=y
CONFIG_USER_ONLY=y
CONFIG_QEMU_INTERP_PREFIX="/usr/gnemul/qemu-m68k"
CONFIG_LINUX_USER=y
TARGET_XML_FILES= /home/coldfunction/qCUDA/qcu-device/gdb-xml/cf-core.xml /home/coldfunction/qCUDA/qcu-device/gdb-xml/cf-fp.xml
TARGET_HAS_BFLT=y
CONFIG_USE_GUEST_BASE=y
CONFIG_I386_DIS=y
CONFIG_M68K_DIS=y
LDFLAGS+= 
QEMU_CFLAGS+=
