/* Automatically generated by create_config - do not modify */
#define TARGET_ARM 1
#define TARGET_NAME "arm"
#define TARGET_ARM 1
#define CONFIG_SOFTMMU 1
#define CONFIG_I386_DIS 1
#define CONFIG_ARM_DIS 1
#define CONFIG_ARM_A64_DIS 1
