/* Automatically generated by create_config - do not modify */
#define TARGET_CRIS 1
#define TARGET_NAME "cris"
#define TARGET_CRIS 1
#define CONFIG_SOFTMMU 1
#define CONFIG_I386_DIS 1
#define CONFIG_CRIS_DIS 1
