/* Automatically generated by create_config - do not modify */
#define TARGET_MICROBLAZE 1
#define TARGET_NAME "microblazeel"
#define TARGET_MICROBLAZE 1
#define CONFIG_SOFTMMU 1
#define CONFIG_I386_DIS 1
#define CONFIG_MICROBLAZE_DIS 1
