# Automatically generated by configure - do not modify
TARGET_MICROBLAZE=y
TARGET_NAME=microblazeel
TARGET_BASE_ARCH=microblaze
TARGET_ABI_DIR=microblaze
CONFIG_SOFTMMU=y
CONFIG_I386_DIS=y
CONFIG_MICROBLAZE_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=
