/* Automatically generated by create_config - do not modify */
#define TARGET_SH4 1
#define TARGET_NAME "sh4"
#define TARGET_SH4 1
#define CONFIG_SOFTMMU 1
#define CONFIG_I386_DIS 1
#define CONFIG_SH4_DIS 1
