/* Automatically generated by create_config - do not modify */
#define TARGET_PPC64 1
#define TARGET_NAME "ppc64"
#define TARGET_PPC 1
#define TARGET_WORDS_BIGENDIAN 1
#define CONFIG_SOFTMMU 1
#define CONFIG_I386_DIS 1
#define CONFIG_PPC_DIS 1
