/* Automatically generated by create_config - do not modify */
#define TARGET_ABI_MIPSO32 1
#define TARGET_MIPS 1
#define TARGET_NAME "mipsel"
#define TARGET_MIPS 1
#define CONFIG_SOFTMMU 1
#define CONFIG_I386_DIS 1
#define CONFIG_MIPS_DIS 1
