/* Automatically generated by create_config - do not modify */
#define TARGET_X86_64 1
#define TARGET_NAME "x86_64"
#define TARGET_I386 1
#define CONFIG_USER_ONLY 1
#define CONFIG_QEMU_INTERP_PREFIX "/usr/gnemul/qemu-x86_64"
#define CONFIG_LINUX_USER 1
#define CONFIG_USE_GUEST_BASE 1
#define CONFIG_I386_DIS 1
#define CONFIG_I386_DIS 1
