/* Automatically generated by create_config - do not modify */
#define TARGET_ALPHA 1
#define TARGET_NAME "alpha"
#define TARGET_ALPHA 1
#define CONFIG_USER_ONLY 1
#define CONFIG_QEMU_INTERP_PREFIX "/usr/gnemul/qemu-alpha"
#define CONFIG_LINUX_USER 1
#define CONFIG_USE_GUEST_BASE 1
#define CONFIG_I386_DIS 1
#define CONFIG_ALPHA_DIS 1
