# Automatically generated by configure - do not modify
TARGET_ABI32=y
TARGET_PPC64=y
TARGET_NAME=ppc64abi32
TARGET_BASE_ARCH=ppc
TARGET_ABI_DIR=ppc
TARGET_WORDS_BIGENDIAN=y
CONFIG_USER_ONLY=y
CONFIG_QEMU_INTERP_PREFIX="/usr/gnemul/qemu-ppc64abi32"
CONFIG_LINUX_USER=y
TARGET_XML_FILES= /home/coldfunction/qCUDA/qcu-device/gdb-xml/power64-core.xml /home/coldfunction/qCUDA/qcu-device/gdb-xml/power-fpu.xml /home/coldfunction/qCUDA/qcu-device/gdb-xml/power-altivec.xml /home/coldfunction/qCUDA/qcu-device/gdb-xml/power-spe.xml
CONFIG_USE_GUEST_BASE=y
CONFIG_I386_DIS=y
CONFIG_PPC_DIS=y
LDFLAGS+= 
QEMU_CFLAGS+=
