/* Automatically generated by create_config - do not modify */
#define TARGET_UNICORE32 1
#define TARGET_NAME "unicore32"
#define TARGET_UNICORE32 1
#define CONFIG_SOFTMMU 1
#define CONFIG_I386_DIS 1
