# Automatically generated by configure - do not modify
TARGET_UNICORE32=y
TARGET_NAME=unicore32
TARGET_BASE_ARCH=unicore32
TARGET_ABI_DIR=unicore32
CONFIG_SOFTMMU=y
CONFIG_I386_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=
