# Automatically generated by configure - do not modify
TARGET_AARCH64=y
TARGET_NAME=aarch64
TARGET_BASE_ARCH=arm
TARGET_ABI_DIR=aarch64
CONFIG_USER_ONLY=y
CONFIG_QEMU_INTERP_PREFIX="/usr/gnemul/qemu-aarch64"
CONFIG_LINUX_USER=y
TARGET_XML_FILES= /home/coldfunction/qCUDA/qcu-device/gdb-xml/aarch64-core.xml /home/coldfunction/qCUDA/qcu-device/gdb-xml/aarch64-fpu.xml /home/coldfunction/qCUDA/qcu-device/gdb-xml/arm-core.xml /home/coldfunction/qCUDA/qcu-device/gdb-xml/arm-vfp.xml /home/coldfunction/qCUDA/qcu-device/gdb-xml/arm-vfp3.xml /home/coldfunction/qCUDA/qcu-device/gdb-xml/arm-neon.xml
TARGET_HAS_BFLT=y
CONFIG_USE_GUEST_BASE=y
CONFIG_I386_DIS=y
CONFIG_ARM_DIS=y
CONFIG_ARM_A64_DIS=y
LDFLAGS+= 
QEMU_CFLAGS+=
