# Automatically generated by configure - do not modify
TARGET_ALPHA=y
TARGET_NAME=alpha
TARGET_BASE_ARCH=alpha
TARGET_ABI_DIR=alpha
CONFIG_SOFTMMU=y
CONFIG_I386_DIS=y
CONFIG_ALPHA_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=
