/* Automatically generated by create_config - do not modify */
#define TARGET_ALPHA 1
#define TARGET_NAME "alpha"
#define TARGET_ALPHA 1
#define CONFIG_SOFTMMU 1
#define CONFIG_I386_DIS 1
#define CONFIG_ALPHA_DIS 1
