# Automatically generated by configure - do not modify
TARGET_PPC=y
TARGET_NAME=ppc
TARGET_BASE_ARCH=ppc
TARGET_ABI_DIR=ppc
TARGET_WORDS_BIGENDIAN=y
CONFIG_USER_ONLY=y
CONFIG_QEMU_INTERP_PREFIX="/usr/gnemul/qemu-ppc"
CONFIG_LINUX_USER=y
TARGET_XML_FILES= /home/coldfunction/qCUDA/qcu-device/gdb-xml/power-core.xml /home/coldfunction/qCUDA/qcu-device/gdb-xml/power-fpu.xml /home/coldfunction/qCUDA/qcu-device/gdb-xml/power-altivec.xml /home/coldfunction/qCUDA/qcu-device/gdb-xml/power-spe.xml
CONFIG_USE_GUEST_BASE=y
CONFIG_I386_DIS=y
CONFIG_PPC_DIS=y
LDFLAGS+= 
QEMU_CFLAGS+=
