/* Automatically generated by create_config - do not modify */
#define TARGET_ABI_MIPSN32 1
#define TARGET_ABI32 1
#define TARGET_MIPS64 1
#define TARGET_NAME "mipsn32el"
#define TARGET_MIPS 1
#define CONFIG_USER_ONLY 1
#define CONFIG_QEMU_INTERP_PREFIX "/usr/gnemul/qemu-mipsn32el"
#define CONFIG_LINUX_USER 1
#define CONFIG_USE_GUEST_BASE 1
#define CONFIG_I386_DIS 1
#define CONFIG_MIPS_DIS 1
