# Automatically generated by configure - do not modify
TARGET_XTENSA=y
TARGET_NAME=xtensa
TARGET_BASE_ARCH=xtensa
TARGET_ABI_DIR=xtensa
CONFIG_SOFTMMU=y
CONFIG_I386_DIS=y
CONFIG_XTENSA_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=
