/* Automatically generated by create_config - do not modify */
#define TARGET_XTENSA 1
#define TARGET_NAME "xtensa"
#define TARGET_XTENSA 1
#define CONFIG_SOFTMMU 1
#define CONFIG_I386_DIS 1
#define CONFIG_XTENSA_DIS 1
