/* Automatically generated by create_config - do not modify */
#define TARGET_UNICORE32 1
#define TARGET_NAME "unicore32"
#define TARGET_UNICORE32 1
#define CONFIG_USER_ONLY 1
#define CONFIG_QEMU_INTERP_PREFIX "/usr/gnemul/qemu-unicore32"
#define CONFIG_LINUX_USER 1
#define CONFIG_USE_GUEST_BASE 1
#define CONFIG_I386_DIS 1
